# 추천 시스템

추천시스템은 사용자가 좋아할 가능성이 높은 아이템(영화, 제품, 음악 등)을 추천하는 시스템이다. 사용자와 아이템의 특성, 과거 상호작용, 유사성 등을 바탕으로 개인화된 추천을 제공한다.

추천 시스템의 주요 유형은 다음과 같다.

1. 콘텐츠 기반 필터링(Content-Based Filtering):
사용자가 과거에 선호한 아이템의 속성과 유사한 아이템을 추천하는 방식이다.
예를 들어 사용자가 액션 영화, SF 영화처럼 특정 장르를 자주 봤다면, 비슷한 장르나 속성을 가진 다른 영화를 추천할 수 있다.

2. 협업 필터링(Collaborative Filtering):
비슷한 사용자들의 행동 패턴이나, 함께 소비된 아이템의 관계를 바탕으로 추천하는 방식이다.
즉, 아이템 자체의 속성보다 사용자-아이템 상호작용 기록을 활용한다.

   2-1. 사용자 기반 협업 필터링:
   비슷한 구매나 평가 패턴을 가진 사용자들을 찾아 추천한다.
   예를 들어 홍길동이 라면, 만두, 김치를 구매했고 신사임당이 라면, 만두를 구매했다면, 두 사용자는 비슷한 소비 패턴을 보인다고 판단할 수 있다. 이 경우 신사임당에게 김치를 추천할 수 있다.

   2-2. 아이템 기반 협업 필터링:
   함께 구매되거나 함께 소비되는 경향이 높은 아이템을 추천한다.
   예를 들어 비빔면과 삼겹살을 같이 구매하는 경우가 많다면, 비빔면을 구매한 사용자에게 삼겹살을 추천할 수 있다.

3. 하이브리드 추천 시스템(Hybrid Recommendation Systems):
콘텐츠 기반 필터링과 협업 필터링을 결합한 방식이다.
협업 필터링은 신규 사용자나 신규 아이템에 대한 정보가 부족할 때 콜드 스타트 문제가 발생할 수 있다. 이를 보완하기 위해 하이브리드 방식은 초기에는 콘텐츠 정보도 활용하고, 이후 상호작용 데이터가 충분히 쌓이면 협업 신호를 함께 반영하여 추천 성능을 높인다.
넷플릭스와 같은 대규모 서비스는 이런 다양한 추천 신호를 복합적으로 활용하는 대표적인 사례로 볼 수 있다.

요즘 추천 시스템은 단순히 한 가지 알고리즘만 쓰기보다, 후보를 빠르게 찾는 단계와 그 후보를 정교하게 재정렬하는 단계를 나누어 여러 모델을 함께 사용하는 경우가 많다.

## 코사인 유사도 cosine similiarity

코사인 유사도(Cosine Similarity)는 두 벡터 간의 유사도를 측정하는 방법으로, 벡터의 방향을 비교하여 얼마나 유사한지를 계산하는 지표이다.

코사인 유사도의 값은 -1에서 1 사이에 있으며, 1에 가까울수록 두 벡터의 방향이 유사하다는 것을 의미한다. 주로 문서의 유사도를 계산하거나, 추천 시스템 등에서 사용된다.


**벡터란?**
벡터는 방향과 크기를 가진 데이터다.

집에서 학교까지 걸어간다고 할 때, 벡터로는 두 가지 정보를 나타낼 수 있다.
- 방향: 집에서 학교로 가는 길의 방향.
- 크기: 집에서 학교까지의 거리.

예를 들어, (1, 2)와 같은 2차원 좌표를 벡터라고 할 수 있다.

**Vector의 크기와 방향**

벡터의 방향과 크기를 따로 구할 수 있다.

1. **벡터의 크기 (Magnitude):** 벡터의 크기는 벡터의 각 성분을 제곱한 후 더한 값을 루트 씌운 것으로 구할 수 있다. 예를 들어, 2차원 벡터 $\vec{v} = (x, y)$의 크기는 다음과 같다.

   $
   \text{크기} = \sqrt{x^2 + y^2}
   $

   3차원 벡터의 경우, $\vec{v} = (x, y, z)$라면 크기는 다음과 같다.

   $
   \text{크기} = \sqrt{x^2 + y^2 + z^2}
   $

2. **벡터의 방향 (Direction):** 벡터의 방향은 벡터의 각 성분을 벡터의 크기로 나눈 정규화된 벡터로 구할 수 있다. 이를 단위 벡터라고도 한다. 벡터 $\vec{v} = (x, y)$의 경우 방향은 다음과 같이 구한다.

   $
   \text{단위 벡터} = \left(\frac{x}{\text{크기}}, \frac{y}{\text{크기}}\right)
   $

   3차원 벡터라면,

   $
   \text{단위 벡터} = \left(\frac{x}{\text{크기}}, \frac{y}{\text{크기}}, \frac{z}{\text{크기}}\right)
   $

In [1]:
import numpy as np

def vec_magnitude_direction(vec):
    # 크기 magnitude
    mag = np.sqrt(np.sum(vec ** 2))
    # 방향 (단위벡터)
    if mag != 0:
        dir = vec / mag
    else:
        dir = np.zeros_like(vec)
    return mag, dir

vec  = np.array([3, 4])
print(vec_magnitude_direction(vec))

vec  = np.array([3, 4, 5])
print(vec_magnitude_direction(vec))

(5.0, array([0.6, 0.8]))
(7.0710678118654755, array([0.42426407, 0.56568542, 0.70710678]))

In [2]:
import numpy as np

def vec_magnitude_direction(vec):
    # 크기 magnitude
    mag = np.linalg.norm(vec)
    # 방향 (단위벡터)
    dir = vec / mag
    return mag, dir

vec  = np.array([3, 4])
print(vec_magnitude_direction(vec))

vec  = np.array([3, 4, 5])
print(vec_magnitude_direction(vec))

(5.0, array([0.6, 0.8]))
(7.0710678118654755, array([0.42426407, 0.56568542, 0.70710678]))

### 두 벡터의 코사인 유사도

두 벡터가 얼마나 비슷한지 측정하는 방법이다. 코사인 유사도는 벡터의 방향을 기준으로 유사도를 측정한다.

**코사인 유사도의 수식**

코사인 유사도는 두 벡터 사이의 코사인을 계산한다. 벡터 $ A $와 $ B $가 주어지면, 코사인 유사도는 다음과 같이 계산된다:

$
Cosine Similarity = \frac{A \cdot B}{||A|| \times ||B||}
$

- $A \cdot B$는 두 벡터의 내적 (dot product)
- $||A||$와 $||B|| $는 각 벡터의 크기 (magnitude)

**코사인 유사도 계산 단계**

1. 벡터의 내적 계산

    두 벡터의 대응하는 원소들을 곱해서 모두 더한다.

    예: 벡터 $ A = (1, 2, 3) $와 $ B = (4, 5, 6) $일 때,

    $
    A \cdot B = (1 \times 4) + (2 \times 5) + (3 \times 6) = 4 + 10 + 18 = 32
    $

2. 벡터의 크기 계산

    각 벡터의 크기는 벡터 원소들의 제곱을 더한 후 제곱근을 취한다.

    예: 벡터 $ A $와 $ B $의 크기

    $||A|| = \sqrt{1^2 + 2^2 + 3^2} = \sqrt{1 + 4 + 9} = \sqrt{14}$
    <br>
    $||B|| = \sqrt{4^2 + 5^2 + 6^2} = \sqrt{16 + 25 + 36} = \sqrt{77}$

3. 코사인 유사도 계산

    내적을 벡터 크기의 곱으로 나눈다.

    $
    \text{Cosine Similarity} = \frac{32}{\sqrt{14} \times \sqrt{77}} = \frac{32}{\sqrt{1078}} = 0.9746318461970763
    $

4. 최종 값

    계산된 값을 통해 두 벡터의 유사도를 측정한다. 값이 1에 가까울수록 두 벡터는 더 유사하고, -1에 가까울수록 더 다르다.



코사인 유사도는 두 벡터가 얼마나 비슷한 방향을 가지고 있는지를 측정한다.

텍스트 분석 등에서 문서 간의 유사도를 계산하는 데 자주 사용된다. 계산 과정은 벡터의 내적과 크기를 구한 후 이를 이용해 최종적으로 유사도를 구하는 것이다.

텍스트 분석등에서는 count를 기반으로 하므로, 모든 vector가 0이상의 값이다. 즉 0~90° 사이의 값이고, 이에 따르는 코사인 유사도는 0 ~ 1 사이의 값이다.

In [5]:
vec_a = np.array([1, 2, 3])
vec_a = np.array([-1, -2, -3])
vec_b = np.array([4, 5, 6])

def cos_similarity(A, B):
    # 두 벡터의 내적 / 두 벡터 크기 곱
    dot_product = A @ B
    norm_A = np.linalg.norm(A)
    norm_B = np.linalg.norm(B)
    return dot_product / (norm_A * norm_B)

cos_similarity(vec_a, vec_b)

-0.9746318461970762

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

vec_a = np.array([1, 2, 3]).reshape(1, -1)
vec_b = np.array([4, 5, 6]).reshape(1, -1)
print(vec_a, vec_b)

# batch차원으로 감싸진 vector를 전달해야 함
cosine_similarity(vec_a, vec_b)

[[1 2 3]] [[4 5 6]]

array([[0.97463185]])

## 컨텐츠 기반 필터링
순수하게 아이템기반으로 유사도를 따져서 추천

1. 컨텐츠의 여러 텍스트정보를 feature vector 변환
2. 코사인유사도 기반으로 컨텐츠간 유사도 계산
3. 유사한 컨텐츠 중에서 평점이 좋은 순(가중평점)으로 추천

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## TMDB 5000 Movie Dataset 구조 이해

이 데이터는 영화 1편을 1행(row)으로 가지는 영화 메타데이터 중심 데이터셋이다.  
영화의 장르, 줄거리, 키워드, 평점, 투표 수, 인기도 같은 정보를 이용해 탐색적 분석이나 추천 시스템 실습을 하기에 적합하다.  
공식 Kaggle 설명에서도 plot, cast, crew, budget, revenue 등 수천 편 영화 정보를 다룰 수 있는 입문용 데이터로 소개된다.

보통 `tmdb_5000_movies.csv`와 `tmdb_5000_credits.csv` 두 파일로 구성된다.  
- movies 파일: 영화 자체의 메타데이터
- credits 파일: 출연진(cast), 제작진(crew) 정보

### 자주 보는 주요 컬럼

1. 영화 기본 식별 정보
- `id`: 영화 고유 ID
- `title`: 영화 제목
- `original_title`: 원제
- `original_language`: 원래 언어
- `release_date`: 개봉일
- `status`: 개봉 상태
- `homepage`: 공식 홈페이지

2. 내용(콘텐츠) 정보
- `genres`: 장르 목록
- `keywords`: 영화 핵심 키워드
- `overview`: 줄거리 요약
- `tagline`: 홍보 문구
- `spoken_languages`: 사용 언어

3. 제작 관련 정보
- `production_companies`: 제작사
- `production_countries`: 제작 국가
- `runtime`: 상영 시간
- `budget`: 제작비
- `revenue`: 흥행 수익

4. 평판/인기 정보
- `popularity`: 인기도 지표
- `vote_average`: 평균 평점
- `vote_count`: 평점 참여 수

5. 별도 credits 파일에서 자주 보는 컬럼
- `cast`: 배우 정보
- `crew`: 감독, 작가 등 제작진 정보 

### 이 데이터셋을 어떻게 바라보면 좋은가?

이 데이터는 크게 보면 다음 3덩어리로 나뉜다.

- 영화가 어떤 작품인가?  
  → `title`, `overview`, `genres`, `keywords`

- 영화가 얼마나 흥행/인기 있었는가?  
  → `popularity`, `vote_average`, `vote_count`, `revenue`

- 누가 만들고 출연했는가?  
  → `cast`, `crew`, `production_companies`

즉 추천 시스템 실습에서는 보통  
`genres`, `keywords`, `overview`, `cast`, `crew` 같은 콘텐츠 정보를 사용하고, 정렬이나 보정에는 `vote_average`, `vote_count`, `popularity`를 함께 활용한다.

In [11]:
movie_df = pd.read_csv('data/tmdb_5000_movies.csv')
columns = ['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity', 'keywords', 'overview']
movie_df = movie_df[columns]
movie_df.head()

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",7.2,11800,150.437577,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",6.9,4500,139.082615,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.3,4466,107.376788,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",7.6,9106,112.312950,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.1,2124,43.926995,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."

In [12]:
movie_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4803 non-null   int64
 1   title         4803 non-null   str
 2   genres        4803 non-null   str
 3   vote_average  4803 non-null   float64
 4   vote_count    4803 non-null   int64
 5   popularity    4803 non-null   float64
 6   keywords      4803 non-null   str
 7   overview      4800 non-null   str
dtypes: float64(2), int64(2), str(4)
memory usage: 300.3 KB

In [13]:
# ast.literal_eval : 문자열로 저장 된 파이썬 리터럴 표현을 실제 파이썬 객채로 안전하게 변환할 때 사용
from ast import literal_eval

def parse_and_join_name(x):
    # 문자열이면 실제 파이썬 객체(list)로 변환
    if isinstance(x ,str):
        x = literal_eval(x)
    # 리스트가 아니면 빈 문자열 반환    
    if not isinstance(x, list):
        return ''
    
    # 각 딕셔너리에서 name값만 꺼내고 내부 공백은 제거한 뒤 하나의 문자열로 합침
    return ' '.join(
        item.get('name','').replace(' ','')
        for item in x
        if isinstance(item, dict)
    )
    
# genres, keywords 컬럼에 동일한 전처리 적용
for col in ['genres', 'keywords']:
    movie_df[col] = movie_df[col].apply(parse_and_join_name)
    
# 변환 결과 확인
movie_df

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
0,19995,Avatar,Action Adventure Fantasy ScienceFiction,7.2,11800,150.437577,cultureclash future spacewar spacecolony socie...,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,6.9,4500,139.082615,ocean drugabuse exoticisland eastindiatradingc...,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,Action Adventure Crime,6.3,4466,107.376788,spy basedonnovel secretagent sequel mi6 britis...,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Action Crime Drama Thriller,7.6,9106,112.312950,dccomics crimefighter terrorist secretidentity...,Following the death of District Attorney Harve...
4,49529,John Carter,Action Adventure ScienceFiction,6.1,2124,43.926995,basedonnovel mars medallion spacetravel prince...,"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,Action Crime Thriller,6.6,238,14.269792,unitedstates–mexicobarrier legs arms paperknif...,El Mariachi just wants to play his guitar and ...
4799,72766,Newlyweds,Comedy Romance,5.9,5,0.642552,,A newlywed couple's honeymoon is upended by th...
4800,231617,"Signed, Sealed, Delivered",Comedy Drama Romance TVMovie,7.0,6,1.444476,date loveatfirstsight narration investigation ...,"""Signed, Sealed, Delivered"" introduces a dedic..."
4801,126186,Shanghai Calling,,5.7,7,0.857008,,When ambitious New York attorney Sam is sent t...
4802,25975,My Date with Drew,Documentary,6.3,16,1.929883,obsession camcorder crush dreamgirl,Ever since the second grade when he first saw ...

## 장르기반 코사인 유사도 계산

In [19]:
# 문자열을 숫자 벡터로 변환 (콘텐츠 기반 추천에서는 영화 간 유사도 계산이 필요하므로 문자열 -> 숫자 변환 필요)
# CountVectorizer : 각 토큰이 문서에 몇 번 등장했는지를 기반으로 벡터화
from sklearn.feature_extraction.text import CountVectorizer

# ngram_range
# : 1개 단어 토큰(unigram)과 2개 단어 토큰(bigram) 등을 고려할 수 있다.
cnt_vectorizer = CountVectorizer(ngram_range=(1, 1))

# 1) 전체 영화의 genres 컬럼을 보고 장르 토큰 사전을 만든다
# 2) 각 영화마다 어떤 토큰이 등장했는지 횟수를 센다
# 3) 각 영화를 숫자 벡터로 변환한다.
movie_genre_mat = cnt_vectorizer.fit_transform(movie_df['genres'])

# CountVectorizer가 생성한 단어 사전
print(cnt_vectorizer.vocabulary_)

# 행 : 영화 개수, 열 : 전체 장르 토큰 개수
print(movie_genre_mat.shape)

# 앞 부분 일부만 배열 형태로 확인
movie_genre_mat[:20, :20].toarray()

{'action': 0, 'adventure': 1, 'fantasy': 8, 'sciencefiction': 15, 'crime': 4, 'drama': 6, 'thriller': 16, 'animation': 2, 'family': 7, 'western': 19, 'comedy': 3, 'romance': 14, 'horror': 11, 'mystery': 13, 'history': 10, 'war': 18, 'music': 12, 'documentary': 5, 'foreign': 9, 'tvmovie': 17}
(4803, 20)

array([[1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [21]:
# 영화간 장르 유사도 비교
genre_sim = cosine_similarity(movie_genre_mat, movie_genre_mat)
print(genre_sim.shape)
genre_sim[:10, :10]

(4803, 4803)

array([[1.        , 0.8660254 , 0.57735027, 0.25      , 0.8660254 ,
        0.8660254 , 0.        , 0.8660254 , 0.57735027, 0.8660254 ],
       [0.8660254 , 1.        , 0.66666667, 0.28867513, 0.66666667,
        1.        , 0.        , 0.66666667, 0.66666667, 1.        ],
       [0.57735027, 0.66666667, 1.        , 0.57735027, 0.66666667,
        0.66666667, 0.        , 0.66666667, 0.33333333, 0.66666667],
       [0.25      , 0.28867513, 0.57735027, 1.        , 0.28867513,
        0.28867513, 0.        , 0.28867513, 0.        , 0.28867513],
       [0.8660254 , 0.66666667, 0.66666667, 0.28867513, 1.        ,
        0.66666667, 0.        , 1.        , 0.33333333, 0.66666667],
       [0.8660254 , 1.        , 0.66666667, 0.28867513, 0.66666667,
        1.        , 0.        , 0.66666667, 0.66666667, 1.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.40824829, 0.        ],
       [0.8660254 , 0.66666667, 0.66666667, 0.28867513, 1.        ,
        0.66666667, 0.        , 1.        , 0.33333333, 0.66666667],
       [0.57735027, 0.66666667, 0.33333333, 0.        , 0.33333333,
        0.66666667, 0.40824829, 0.33333333, 1.        , 0.66666667],
       [0.8660254 , 1.        , 0.66666667, 0.28867513, 0.66666667,
        1.        , 0.        , 0.66666667, 0.66666667, 1.        ]])

In [24]:
# 각 영화별 다른 영화들과의 유사도를 오름차순으로 정렬한 뒤, 열 순서를 뒤집어 내림차순(유사도 높은 순) 인덱스를 만든다.
movie_idx_by_genre_sim_desc = genre_sim.argsort(axis=-1)[:, ::-1]
print(movie_idx_by_genre_sim_desc.shape)

# 0번 영화와 유사도가 가장 높은 10개의 영화 인덱스
print(movie_idx_by_genre_sim_desc[0, :10])

(4803, 4803)
[   0  870   46   10  232  813 3494   61   14 1652]

In [25]:
# 0번 영화와 유사도가 가장 높은 10개의 영화
movie_df.iloc[movie_idx_by_genre_sim_desc[0, :10]]

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
0,19995,Avatar,Action Adventure Fantasy ScienceFiction,7.2,11800,150.437577,cultureclash future spacewar spacecolony socie...,"In the 22nd century, a paraplegic Marine is di..."
870,8536,Superman II,Action Adventure Fantasy ScienceFiction,6.5,629,30.515175,savingtheworld dccomics sequel superhero based...,Three escaped criminals from the planet Krypto...
46,127585,X-Men: Days of Future Past,Action Adventure Fantasy ScienceFiction,7.5,6032,118.078691,1970s mutant timetravel marvelcomic basedoncom...,The ultimate X-Men ensemble fights a war for t...
10,1452,Superman Returns,Adventure Fantasy Action ScienceFiction,5.4,1400,57.925623,savingtheworld dccomics invulnerability sequel...,Superman returns to discover his 5-year absenc...
232,76170,The Wolverine,Action ScienceFiction Adventure Fantasy,6.3,4053,15.953444,japan samurai mutant worldwari marvelcomic sup...,Wolverine faces his ultimate nemesis - and tes...
813,1924,Superman,Action Adventure Fantasy ScienceFiction,6.9,1022,48.507081,savingtheworld journalist dccomics crimefighte...,Mild-mannered Clark Kent works as a reporter a...
3494,27549,Beastmaster 2: Through the Portal of Time,Action Adventure Fantasy ScienceFiction,4.6,17,1.478505,basedonnovel timetravel sequel psychotronic sw...,"Mark Singer returns as Dar, the warrior who ca..."
61,76757,Jupiter Ascending,ScienceFiction Fantasy Action Adventure,5.2,2768,85.369080,jupiter space womandirector 3d interspeciesrom...,In a universe where human genetic material is ...
14,49521,Man of Steel,Action Adventure Fantasy ScienceFiction,6.5,6359,99.398009,savingtheworld dccomics superhero basedoncomic...,A young boy learns that he has extraordinary p...
1652,14164,Dragonball Evolution,Action Adventure Fantasy ScienceFiction Thriller,2.9,462,21.677732,karate superhero revenge dragon duringcreditss...,The young warrior Son Goku sets out on a quest...

In [26]:
# 영화 대부와 높은 장르 유사도를 가진 영화 조회
title = 'The Godfather'
index = movie_df[movie_df['title'] == title].index.values[0]
rcmd_movie_df = movie_df.iloc[movie_idx_by_genre_sim_desc[index, :20]]
rcmd_movie_df.sort_values('vote_average', ascending=False)[:10]

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
3337,238,The Godfather,Drama Crime,8.4,5893,143.659698,italy loveatfirstsight lossoffather patriarch ...,"Spanning the years 1945 to 1955, a chronicle o..."
1663,311,Once Upon a Time in America,Drama Crime,8.2,1069,49.336397,lifeanddeath corruption streetgang rape sadist...,A former Prohibition-era Jewish gangster retur...
3866,598,City of God,Drama Crime,8.1,1814,44.356711,malenudity streetgang brazilian photographer 1...,Cidade de Deus is a shantytown that started du...
3701,641,Requiem for a Dream,Crime Drama,7.9,2443,11.573034,drugaddiction junkie heroin speed diet unsocia...,The hopes and dreams of four ambitious people ...
3887,627,Trainspotting,Drama Crime,7.8,2655,63.513324,londonengland alcohol sex basedonnovel drugadd...,"Renton, deeply immersed in the Edinburgh drug ..."
883,640,Catch Me If You Can,Drama Crime,7.7,3795,73.944049,conman biography fbiagent overheadcamerashot a...,"A true story about Frank Abagnale Jr. who, bef..."
3699,1429,25th Hour,Crime Drama,7.2,629,30.196039,prison prisoner dream drugdealer nightclub ame...,The filmed adaptation from David Benioff's nov...
2448,10673,Wall Street,Crime Drama,7.0,546,24.898687,power fraud broker wallstreet finances lawyer ...,A young and impatient stockbroker is willing t...
2839,10220,Rounders,Drama Crime,6.9,439,18.422008,gambling law compulsivegambling roulette gain,A young man is a reformed gambler who must ret...
3348,398,Capote,Crime Drama,6.8,384,17.434862,gay self-fulfillingprophecy basedonnovel journ...,"A biopic of the writer, Truman Capote and his ..."

In [29]:
# 영화명을 전달하면 장르 유사도가 높은 영화 중 평점이 상위인 영화 10건을 추천하는 함수
def recommand_genre_similar_movies(title, top_n=10):
    # 제목으로 영화 인덱스 조회
    index = movie_df[movie_df['title'] == title].index.values[0]
    # 장르 유사도 상위 top_n * 2 조회
    rcmd_movie_df = movie_df.iloc[movie_idx_by_genre_sim_desc[index, :top_n*2]]
    
    # 조회한 영화는 제외
    rcmd_movie_df = rcmd_movie_df[rcmd_movie_df.index != index]
    # 평점 상위 top_n건 추천
    return rcmd_movie_df.sort_values('vote_average', ascending=False)[:top_n]

recommand_genre_similar_movies('The Dark Knight Rises', 15)

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
1850,111,Scarface,Action Crime Drama Thriller,8.0,2948,70.105981,miami corruption capitalism cuba prohibition b...,After getting a green card in exchange for ass...
1052,2034,Training Day,Action Crime Drama Thriller,7.3,1634,52.081131,policebrutality warondrugs drugtraffic drugdea...,On his first day on the job as a narcotics off...
2435,7304,Running Scared,Action Crime Drama Thriller,7.0,331,19.311572,icehockey racism pedophile throatslitting shot...,"After a drug-op gone bad, Joey Gazelle is put ..."
3316,11022,Narc,Action Crime Drama Thriller,6.8,142,8.526635,assertion investigation internalaffairs narcot...,"An undercover narc dies, the investigation sta..."
919,2112,Payback,Drama Action Thriller Crime,6.7,548,17.457947,newyork heroin money criminal,"With friends like these, who needs enemies? Th..."
1245,62835,Colombiana,Action Thriller Crime Drama,6.5,824,33.785969,streetgang uncle femaleassassin witnesstomurder,"Zoe Saldana plays a young woman who, after wit..."
1049,9869,Patriot Games,Drama Action Thriller Crime,6.3,433,19.637704,assassination assassin repayment ira jackryan,When CIA Analyst Jack Ryan interferes with an ...
4099,7873,Harsh Times,Crime Drama Thriller Action,6.3,197,12.999023,watchingamovie playingpool vinegar,Jim Davis is an ex-Army Ranger who finds himse...
2154,1266,Street Kings,Action Crime Drama Thriller,6.3,363,18.666876,police losangeles,Tom Ludlow is a disillusioned L.A. Police Offi...
1281,10428,Hackers,Action Crime Thriller Drama,6.2,398,17.842246,femalenudity hacker nudity computervirus virtu...,"Along with his new friends, a teenager who was..."
747,82682,Gangster Squad,Crime Drama Action Thriller,6.2,1778,29.041198,losangeles gangster,"Los Angeles, 1949. Ruthless, Brooklyn-born mob..."
1178,7461,Vantage Point,Drama Action Thriller Crime,6.2,716,24.862767,bomb terror spain usapresident terrorist warag...,The attempted assassination of the American Pr...
629,136797,Need for Speed,Action Crime Drama Thriller,6.1,1520,54.814890,streetrace supercars superspeed car basedonvid...,The film revolves around a local street-racer ...
405,9615,The Fast and the Furious: Tokyo Drift,Action Crime Drama Thriller,6.1,1705,8.282876,carrace carjourney carmechanic auto cargarage ...,"In order to avoid a jail sentence, Sean Boswel..."
1853,77866,Contraband,Thriller Action Drama Crime,6.1,770,31.364901,headwound criminal securityguard contraband,When his brother-in-law runs afoul of a drug l...

### 평가 횟수에 대한 가중치가 부여된 평점(Weighted Rating) 적용


$$
가중 평점(Weighted Rating) = (v/(v+m)) * R + (m/(v+m)) * C
$$


| 기호 | 의미                        | 예시      |
| -- | ------------------------- | ------- |
| v  | 이 영화에 평점을 준 사람 수 vote_count         | 예: 30명  |
| R  | 이 영화의 평균 평점 vote_average               | 예: 9.0점 |
| m  | 믿을 만한 평가가 되려면 필요한 최소 평가 수. 임계치 설정 | 예: 100명 |
| C  | 전체 영화의 평균 평점. 전체적으로 평점이 후한 편인지, 박한 편인지 반영. vote_average               | 예: 7.0점 |

In [30]:
# vote_count 분포
movie_df['vote_count'].describe()

count     4803.000000
mean       690.217989
std       1234.585891
min          0.000000
25%         54.000000
50%        235.000000
75%        737.000000
max      13752.000000
Name: vote_count, dtype: float64

In [34]:
# 최소 투표 임계치 설정
m = movie_df['vote_count'].quantile(0.6)    # 상위 40% 수치
print(m)

# 전체 영화 평점
C = movie_df['vote_average'].mean()
print(C)

370.1999999999998
6.092171559442016

In [37]:
# 가중 평점 연산 함수
def weighted_vote_average(movie):
    v = movie['vote_count']
    R = movie['vote_average']
    return (v / (v + m)) * R + (m / (v + m)) * C

movie_df['weighted_vote_average'] = movie_df.apply(weighted_vote_average, axis=1)
movie_df

,id,title,genres,vote_average,vote_count,popularity,keywords,overview,weighted_vote_average
0,19995,Avatar,Action Adventure Fantasy ScienceFiction,7.2,11800,150.437577,cultureclash future spacewar spacecolony socie...,"In the 22nd century, a paraplegic Marine is di...",7.166301
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,6.9,4500,139.082615,ocean drugabuse exoticisland eastindiatradingc...,"Captain Barbossa, long believed to be dead, ha...",6.838594
2,206647,Spectre,Action Adventure Crime,6.3,4466,107.376788,spy basedonnovel secretagent sequel mi6 britis...,A cryptic message from Bond’s past sends him o...,6.284091
3,49026,The Dark Knight Rises,Action Crime Drama Thriller,7.6,9106,112.312950,dccomics crimefighter terrorist secretidentity...,Following the death of District Attorney Harve...,7.541095
4,49529,John Carter,Action Adventure ScienceFiction,6.1,2124,43.926995,basedonnovel mars medallion spacetravel prince...,"John Carter is a war-weary, former military ca...",6.098838
...,...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,Action Crime Thriller,6.6,238,14.269792,unitedstates–mexicobarrier legs arms paperknif...,El Mariachi just wants to play his guitar and ...,6.290894
4799,72766,Newlyweds,Comedy Romance,5.9,5,0.642552,,A newlywed couple's honeymoon is upended by th...,6.089611
4800,231617,"Signed, Sealed, Delivered",Comedy Drama Romance TVMovie,7.0,6,1.444476,date loveatfirstsight narration investigation ...,"""Signed, Sealed, Delivered"" introduces a dedic...",6.106650
4801,126186,Shanghai Calling,,5.7,7,0.857008,,When ambitious New York attorney Sam is sent t...,6.084894
4802,25975,My Date with Drew,Documentary,6.3,16,1.929883,obsession camcorder crush dreamgirl,Ever since the second grade when he first saw ...,6.100782

In [38]:
# 영화명을 전달하면 장르 유사도가 높은 영화 중 "가중평점"이 상위인 영화 10건을 추천하는 함수
def recommand_genre_similar_movies(title, top_n=10):
    # 제목으로 영화 인덱스 조회
    try:
        index = movie_df[movie_df['title'] == title].index.values[0]
    except:
        raise ValueError(f"해당 영화는 존재하지 않습니다. : {title}")

    # 장르 유사도 상위 top_n * 2 조회
    rcmd_movie_df = movie_df.iloc[movie_idx_by_genre_sim_desc[index, :top_n*2]]
    
    # 조회한 영화는 제외
    rcmd_movie_df = rcmd_movie_df[rcmd_movie_df.index != index]
    # 평점 상위 top_n건 추천
    return rcmd_movie_df.sort_values('weighted_vote_average', ascending=False)[:top_n]

recommand_genre_similar_movies('Avatar', 10)

,id,title,genres,vote_average,vote_count,popularity,keywords,overview,weighted_vote_average
46,127585,X-Men: Days of Future Past,Action Adventure Fantasy ScienceFiction,7.5,6032,118.078691,1970s mutant timetravel marvelcomic basedoncom...,The ultimate X-Men ensemble fights a war for t...,7.418594
322,18,The Fifth Element,Adventure Fantasy Action Thriller ScienceFiction,7.3,3885,109.528572,clone taxi cyborg egypt future stowaway spacet...,"In 2257, a taxi driver is unintentionally give...",7.194920
813,1924,Superman,Action Adventure Fantasy ScienceFiction,6.9,1022,48.507081,savingtheworld journalist dccomics crimefighte...,Mild-mannered Clark Kent works as a reporter a...,6.685190
14,49521,Man of Steel,Action Adventure Fantasy ScienceFiction,6.5,6359,99.398009,savingtheworld dccomics superhero basedoncomic...,A young boy learns that he has extraordinary p...,6.477564
870,8536,Superman II,Action Adventure Fantasy ScienceFiction,6.5,629,30.515175,savingtheworld dccomics sequel superhero based...,Three escaped criminals from the planet Krypto...,6.348901
232,76170,The Wolverine,Action ScienceFiction Adventure Fantasy,6.3,4053,15.953444,japan samurai mutant worldwari marvelcomic sup...,Wolverine faces his ultimate nemesis - and tes...,6.282606
3208,333355,Star Wars: Clone Wars: Volume 1,Action Adventure Animation Fantasy ScienceFiction,8.0,27,1.881466,war spaceopera clonetroopers,"The Saga continues with the Emmy-winning ""Star...",6.221858
1390,12437,Underworld: Rise of the Lycans,Fantasy Action Adventure ScienceFiction Thriller,6.2,1428,51.927471,prison underworld slavery castle vampire war w...,"A prequel to the first two Underworld films, t...",6.177801
1191,11551,Small Soldiers,Comedy Adventure Fantasy ScienceFiction Action,6.2,511,23.088571,defenseindustry toyshop technicaltoy soldier p...,When missile technology is used to enhance toy...,6.154700
1932,24264,Sheena,Action Adventure Comedy Fantasy ScienceFiction,5.0,22,4.020194,africa mercenary adventure femalehero junglegirl,Sheena's white parents are killed while on Saf...,6.030907

## genres + keywords 를 함께 사용한 콘텐츠 기반 필터링
genres와 keywords를 하나의 텍스트로 합친 뒤 다시 벡터화 하여, 장르만 사용했을 때와 추천 결과가 어떻게 달라지는지 비교해본다.

In [ ]:
movie_df['gen_key'] = movie_df['genres'] + ' ' + movie_df['keywords']

In [58]:
# 문자열을 숫자 벡터로 변환 (콘텐츠 기반 추천에서는 영화 간 유사도 계산이 필요하므로 문자열 -> 숫자 변환 필요)
# CountVectorizer : 각 토큰이 문서에 몇 번 등장했는지를 기반으로 벡터화
from sklearn.feature_extraction.text import CountVectorizer

# ngram_range
# : 1개 단어 토큰(unigram)과 2개 단어 토큰(bigram) 등을 고려할 수 있다.
cnt_vectorizer = CountVectorizer(ngram_range=(1, 2))

# 1) 전체 영화의 genres 컬럼을 보고 장르 토큰 사전을 만든다
# 2) 각 영화마다 어떤 토큰이 등장했는지 횟수를 센다
# 3) 각 영화를 숫자 벡터로 변환한다.
movie_gen_key = cnt_vectorizer.fit_transform(movie_df['gen_key'])

# CountVectorizer가 생성한 단어 사전
print(cnt_vectorizer.vocabulary_)

# 행 : 영화 개수, 열 : 전체 장르 토큰 개수
print(movie_gen_key.shape)

# 앞 부분 일부만 배열 형태로 확인
movie_gen_key[:30, :30].toarray()

{'action': 166, 'adventure': 399, 'fantasy': 13653, 'sciencefiction': 32421, 'cultureclash': 9169, 'future': 15487, 'spacewar': 35082, 'spacecolony': 34964, 'society': 34700, 'spacetravel': 35061, 'futuristic': 15527, 'romance': 31249, 'space': 34936, 'alien': 941, 'tribe': 38971, 'alienplanet': 1055, 'cgi': 6240, 'marine': 22784, 'soldier': 34743, 'battle': 3379, 'loveaffair': 22121, 'antiwar': 1676, 'powerrelations': 28732, 'mindandsoul': 23723, '3d': 98, 'action adventure': 168, 'adventure fantasy': 442, 'fantasy sciencefiction': 13753, 'sciencefiction cultureclash': 32467, 'cultureclash future': 9171, 'future spacewar': 15514, 'spacewar spacecolony': 35083, 'spacecolony society': 34966, 'society spacetravel': 34706, 'spacetravel futuristic': 35068, 'futuristic romance': 15532, 'romance space': 31548, 'space alien': 34938, 'alien tribe': 996, 'tribe alienplanet': 38972, 'alienplanet cgi': 1058, 'cgi marine': 6244, 'marine soldier': 22791, 'soldier battle': 34749, 'battle loveaffair': 3393, 'loveaffair antiwar': 22122, 'antiwar powerrelations': 1678, 'powerrelations mindandsoul': 28733, 'mindandsoul 3d': 23724, 'ocean': 26494, 'drugabuse': 11483, 'exoticisland': 12877, 'eastindiatradingcompany': 12051, 'loveofone': 22162, 'slife': 34368, 'traitor': 38744, 'shipwreck': 33721, 'strongwoman': 35964, 'ship': 33687, 'alliance': 1094, 'calypso': 5490, 'afterlife': 635, 'fighter': 14396, 'pirate': 27943, 'swashbuckler': 36762, 'aftercreditsstinger': 598, 'fantasy action': 13654, 'action ocean': 226, 'ocean drugabuse': 26496, 'drugabuse exoticisland': 11487, 'exoticisland eastindiatradingcompany': 12883, 'eastindiatradingcompany loveofone': 12054, 'loveofone slife': 22163, 'slife traitor': 34407, 'traitor shipwreck': 38759, 'shipwreck strongwoman': 33733, 'strongwoman ship': 35969, 'ship alliance': 33689, 'alliance calypso': 1095, 'calypso afterlife': 5491, 'afterlife fighter': 639, 'fighter pirate': 14398, 'pirate swashbuckler': 27951, 'swashbuckler aftercreditsstinger': 36763, 'crime': 8711, 'spy': 35407, 'basedonnovel': 3015, 'secretagent': 32854, 'sequel': 33157, 'mi6': 23528, 'britishsecretservice': 4940, 'unitedkingdom': 39518, 'adventure crime': 425, 'crime spy': 8869, 'spy basedonnovel': 35413, 'basedonnovel secretagent': 3133, 'secretagent sequel': 32873, 'sequel mi6': 33188, 'mi6 britishsecretservice': 23529, 'britishsecretservice unitedkingdom': 4946, 'drama': 10936, 'thriller': 37850, 'dccomics': 9584, 'crimefighter': 8913, 'terrorist': 37573, 'secretidentity': 32900, 'burglar': 5280, 'hostagedrama': 18361, 'timebomb': 38323, 'gothamcity': 16380, 'vigilante': 40065, 'cover': 8601, 'up': 39600, 'superhero': 36333, 'villainess': 40127, 'tragichero': 38656, 'terrorism': 37561, 'destruction': 10149, 'catwoman': 6113, 'catburglar': 6052, 'imax': 18824, 'flood': 14790, 'criminalunderworld': 8969, 'batman': 3373, 'action crime': 188, 'crime drama': 8765, 'drama thriller': 11296, 'thriller dccomics': 37957, 'dccomics crimefighter': 9586, 'crimefighter terrorist': 8923, 'terrorist secretidentity': 37594, 'secretidentity burglar': 32903, 'burglar hostagedrama': 5284, 'hostagedrama timebomb': 18365, 'timebomb gothamcity': 38325, 'gothamcity vigilante': 16383, 'vigilante cover': 40068, 'cover up': 8602, 'up superhero': 39615, 'superhero villainess': 36359, 'villainess tragichero': 40130, 'tragichero terrorism': 38661, 'terrorism destruction': 37566, 'destruction catwoman': 10150, 'catwoman catburglar': 6114, 'catburglar imax': 6053, 'imax flood': 18831, 'flood criminalunderworld': 14792, 'criminalunderworld batman': 8971, 'mars': 22902, 'medallion': 23194, 'princess': 29013, 'steampunk': 35626, 'martian': 22973, 'escape': 12542, 'edgarriceburroughs': 12114, 'alienrace': 1067, 'superhumanstrength': 36381, 'marscivilization': 22910, 'swordandplanet': 36859, '19thcentury': 78, 'adventure sciencefiction': 494, 'sciencefiction basedonnovel': 32445, 'basedonnovel mars': 3096, 'mars medallion': 22905, 'medallion spacetravel': 23198, 'spacetravel princess': 35073, 'princess alien': 29014, 'alien steampunk': 988, 'steampunk martian': 35632, 'martian escape': 22976, 'escape edgarriceburroughs': 12557, 'edgarriceburroughs alienrace': 12115, 'alienrace superhumanstrength': 1069, 'superhumanstrength marscivilization': 36385, 'marscivilization swordandplanet': 22911, 'swordandplanet 19thcentury': 36860, '19thcentury 3d': 80, 'dualidentity': 11655, 'amnesia': 1300, 'sandstorm': 32072, 'forgiveness': 15022, 'spider': 35183, 'wretch': 41792, 'deathofafriend': 9716, 'egomania': 12142, 'sand': 32061, 'narcism': 25372, 'hostility': 18380, 'marvelcomic': 22989, 'revenge': 30757, 'adventure dualidentity': 434, 'dualidentity amnesia': 11656, 'amnesia sandstorm': 1319, 'sandstorm loveofone': 32075, 'slife forgiveness': 34380, 'forgiveness spider': 15032, 'spider wretch': 35188, 'wretch deathofafriend': 41793, 'deathofafriend egomania': 9719, 'egomania sand': 12143, 'sand narcism': 32062, 'narcism hostility': 25373, 'hostility marvelcomic': 18384, 'marvelcomic sequel': 22994, 'sequel superhero': 33211, 'superhero revenge': 36352, 'animation': 1511, 'family': 13317, 'hostage': 18328, 'magic': 22420, 'horse': 18237, 'fairytale': 13175, 'musical': 24942, 'tower': 38576, 'blondewoman': 4268, 'selfishness': 33078, 'healingpower': 17155, 'basedonfairytale': 2990, 'duringcreditsstinger': 11721, 'healinggift': 17153, 'animalsidekick': 1494, 'animation family': 1534, 'family hostage': 13425, 'hostage magic': 18341, 'magic horse': 22438, 'horse fairytale': 18243, 'fairytale musical': 13184, 'musical princess': 24991, 'princess animation': 29015, 'animation tower': 1557, 'tower blondewoman': 38577, 'blondewoman selfishness': 4269, 'selfishness healingpower': 33079, 'healingpower basedonfairytale': 17156, 'basedonfairytale duringcreditsstinger': 2992, 'duringcreditsstinger healinggift': 11759, 'healinggift animalsidekick': 17154, 'basedoncomicbook': 2946, 'vision': 40320, 'superheroteam': 36368, 'marvelcinematicuniverse': 22984, 'sciencefiction marvelcomic': 32529, 'superhero basedoncomicbook': 36336, 'basedoncomicbook vision': 2985, 'vision superheroteam': 40330, 'superheroteam duringcreditsstinger': 36371, 'duringcreditsstinger marvelcinematicuniverse': 11770, 'marvelcinematicuniverse 3d': 22985, 'witch': 41373, 'broom': 5018, 'schoolofwitchcraft': 32375, 'wizardry': 41452, 'apparition': 1740, 'teenagecrush': 37213, 'werewolf': 40974, 'fantasy family': 13694, 'family witch': 13540, 'witch magic': 41393, 'magic broom': 22426, 'broom schoolofwitchcraft': 5020, 'schoolofwitchcraft wizardry': 32380, 'wizardry apparition': 41453, 'apparition teenagecrush': 1741, 'teenagecrush werewolf': 37222, 'superpowers': 36462, 'clarkkent': 7031, 'brucewayne': 5140, 'dcextendeduniverse': 9602, 'fantasy dccomics': 13680, 'dccomics vigilante': 9601, 'vigilante superhero': 40074, 'basedoncomicbook revenge': 2977, 'revenge superpowers': 30817, 'superpowers clarkkent': 36464, 'clarkkent brucewayne': 7032, 'brucewayne dcextendeduniverse': 5141, 'savingtheworld': 32206, 'invulnerability': 19678, 'kryptonite': 20802, 'lexluthor': 21293, 'action sciencefiction': 238, 'sciencefiction savingtheworld': 32561, 'savingtheworld dccomics': 32211, 'dccomics invulnerability': 9590, 'invulnerability sequel': 19679, 'basedoncomicbook kryptonite': 2966, 'kryptonite superpowers': 20803, 'superpowers superhumanstrength': 36473, 'superhumanstrength lexluthor': 36384, 'killing': 20637, 'undercover': 39347, 'adventure action': 401, 'action thriller': 254, 'thriller crime': 37952, 'crime killing': 8813, 'killing undercover': 20647, 'undercover secretagent': 39374, 'secretagent britishsecretservice': 32857, 'fortuneteller': 15068, 'bondage': 4530, 'monster': 24180, 'captain': 5680, 'cardgame': 5788, 'compass': 7922, 'daughter': 9515, 'action witch': 261, 'witch fortuneteller': 41386, 'fortuneteller bondage': 15069, 'bondage exoticisland': 4532, 'exoticisland monster': 12885, 'monster captain': 24183, 'captain cardgame': 5683, 'cardgame eastindiatradingcompany': 5790, 'eastindiatradingcompany compass': 12052, 'compass ship': 7925, 'ship daughter': 33691, 'daughter pirate': 9551, 'western': 40992, 'texas': 37631, 'survivor': 36643, 'texasranger': 37654, 'partner': 27327, 'outlaw': 26897, 'lawyer': 21088, 'train': 38679, 'loneranger': 21696, 'comanche': 7421, 'theloneranger': 37752, 'tonto': 38449, 'adventure western': 517, 'western texas': 41041, 'texas horse': 37642, 'horse survivor': 18257, 'survivor texasranger': 36650, 'texasranger partner': 37656, 'partner outlaw': 27336, 'outlaw escape': 26898, 'escape lawyer': 12564, 'lawyer train': 21120, 'train loneranger': 38685, 'loneranger comanche': 21697, 'comanche theloneranger': 7422, 'theloneranger tonto': 37753, 'superhuman': 36374, 'alieninvasion': 1028, 'reboot': 30109, 'dccomics superhero': 9599, 'basedoncomicbook superhuman': 2981, 'superhuman alieninvasion': 36375, 'alieninvasion reboot': 1043, 'reboot superpowers': 30113, 'superpowers dcextendeduniverse': 36465, 'fictionalplace': 14328, 'brothersisterrelationship': 5102, 'lion': 21480, 'humanbeing': 18525, 'leapintime': 21139, 'matteroflifeanddeath': 23129, 'faith': 13191, 'uncle': 39315, 'narnia': 25388, 'fantasyworld': 13786, 'adventure family': 441, 'family fantasy': 13393, 'fantasy basedonnovel': 13664, 'basedonnovel fictionalplace': 3061, 'fictionalplace brothersisterrelationship': 14329, 'brothersisterrelationship lion': 5119, 'lion humanbeing': 21486, 'humanbeing wretch': 18530, 'wretch leapintime': 41796, 'leapintime matteroflifeanddeath': 21142, 'matteroflifeanddeath faith': 23132, 'faith uncle': 13213, 'uncle narnia': 39321, 'narnia fantasyworld': 25389, 'newyork': 25864, 'shield': 33678, 'sciencefiction action': 32423, 'adventure newyork': 480, 'newyork shield': 25929, 'shield marvelcomic': 33680, 'marvelcomic superhero': 22996, 'basedoncomicbook alieninvasion': 2948, 'alieninvasion superheroteam': 1047, 'superheroteam aftercreditsstinger': 36369, 'aftercreditsstinger duringcreditsstinger': 612, 'sea': 32753, 'mutiny': 25162, 'sword': 36845, 'primeminister': 28986, 'sailing': 31983, 'silver': 34001, 'duke': 11703, 'mermaid': 23418, 'action fantasy': 200, 'fantasy sea': 13755, 'sea captain': 32757, 'captain mutiny': 5685, 'mutiny sword': 25168, 'sword primeminister': 36857, 'primeminister sailing': 28991, 'sailing silver': 31990, 'silver ship': 34003, 'ship duke': 33695, 'duke mermaid': 11706, 'mermaid pirate': 23420, 'pirate soldier': 27950, 'battle swashbuckler': 3403, 'aftercreditsstinger 3d': 601, 'comedy': 7452, 'timetravel': 38352, 'timemachine': 38335, 'fictionalgovernmentagency': 14320, 'seeingthefuture': 33048, 'changinghistory': 6306, 'action comedy': 184, 'comedy sciencefiction': 7717, 'sciencefiction timetravel': 32592, 'timetravel timemachine': 38384, 'timemachine alien': 38336, 'alien fictionalgovernmentagency': 960, 'fictionalgovernmentagency seeingthefuture': 14321, 'seeingthefuture changinghistory': 33049, 'corruption': 8398, 'elves': 12252, 'dwarves': 11811, 'orcs': 26760, 'middle': 23561, 'earth': 12019, 'tolkien': 38432, 'hobbit': 17809, 'dragon': 10908, 'unlikelyfriendship': 39539, 'epicbattle': 12484, 'swordandsorcery': 36863, 'fantasy corruption': 13678, 'corruption elves': 8409, 'elves dwarves': 12255, 'dwarves orcs': 11814, 'orcs middle': 26763, 'middle earth': 23562, 'earth tolkien': 12024, 'tolkien hobbit': 38434, 'hobbit dragon': 17811, 'dragon battle': 10912, 'battle unlikelyfriendship': 3405, 'unlikelyfriendship epicbattle': 39544, 'epicbattle swordandsorcery': 12486, 'lossoffather': 21878, 'serum': 33279, 'scientificexperiment': 32611, 'spiderbite': 35189, 'maskedvigilante': 23038, 'geneticengineering': 15882, 'socialoutcast': 34680, 'fantasy lossoffather': 13719, 'lossoffather vigilante': 21903, 'vigilante serum': 40072, 'serum marvelcomic': 33280, 'marvelcomic scientificexperiment': 22993, 'scientificexperiment spiderbite': 32612, 'spiderbite maskedvigilante': 35191, 'maskedvigilante reboot': 23041, 'superpowers geneticengineering': 36469, 'geneticengineering socialoutcast': 15886, 'socialoutcast duringcreditsstinger': 34683, 'robinhood': 31107, 'archer': 1818, 'knight': 20759, 'sherwoodforest': 33676, 'bowandarrow': 4661, 'middleages': 23569, 'medieval': 23244, 'kingofengland': 20689, 'adventure robinhood': 490, 'robinhood archer': 31108, 'archer knight': 1820, 'knight sherwoodforest': 20765, 'sherwoodforest bowandarrow': 33677, 'bowandarrow middleages': 4664, 'middleages medieval': 23573, 'medieval kingofengland': 23246, 'wizard': 41444, 'fantasy elves': 13689, 'orcs hobbit': 26761, 'dragon wizard': 10924, 'wizard swordandsorcery': 41449, 'england': 12386, 'experiment': 12916, 'lordship': 21738, 'polarbear': 28207, 'orphan': 26817, 'animal': 1449, 'basedonyoungadultnovel': 3306, 'fantasy england': 13691, 'england compass': 12397, 'compass experiment': 7923, 'experiment lordship': 12925, 'lordship uncle': 21741, 'uncle polarbear': 39322, 'polarbear orphan': 28208, 'orphan animal': 26821, 'animal basedonyoungadultnovel': 1454, 'filmbusiness': 14431, 'screenplay': 32688, 'showbusiness': 33884, 'filmmaking': 14472, 'filmproducer': 14487, 'indigenous': 19182, 'dinosaur': 10323, 'adventure drama': 433, 'drama action': 10938, 'action filmbusiness': 201, 'filmbusiness screenplay': 14434, 'screenplay showbusiness': 32690, 'showbusiness filmmaking': 33887, 'filmmaking filmproducer': 14475, 'filmproducer exoticisland': 14489, 'monster indigenous': 24196, 'indigenous ship': 19185, 'ship dinosaur': 33692, 'iceberg': 18680, 'panic': 27068, 'titanic': 38401, 'oceanliner': 26509, 'epic': 12476, 'richwoman': 30890, 'poorman': 28531, 'love': 22057, 'disaster': 10387, 'tragiclove': 38662, 'classdifferences': 7041, 'starcrossedlovers': 35568, 'steerage': 35644, 'salvage': 32039, 'richsnob': 30886, '1910s': 15, 'drama romance': 11242, 'romance thriller': 31571, 'thriller shipwreck': 38188, 'shipwreck iceberg': 33725, 'iceberg ship': 18682, 'ship panic': 33708, 'panic titanic': 27074, 'titanic oceanliner': 38403, 'oceanliner epic': 26510, 'epic richwoman': 12482, 'richwoman poorman': 30891, 'poorman love': 28532, 'love disaster': 22073, 'disaster tragiclove': 10399, 'tragiclove classdifferences': 38663, 'classdifferences imax': 7045, 'imax starcrossedlovers': 18837, 'starcrossedlovers steerage': 35571, 'steerage salvage': 35645, 'salvage richsnob': 32040, 'richsnob 3d': 30887, '3d 1910s': 99, 'civilwar': 7012, 'war': 40520, 'sciencefiction civilwar': 32458, 'civilwar war': 7023, 'war marvelcomic': 40585, 'basedoncomicbook imax': 2963, 'imax aftercreditsstinger': 18826, 'fight': 14355, 'navy': 25500, 'mindreading': 23740, 'hongkong': 18016, 'soccer': 34638, 'scientist': 32615, 'fictionalwar': 14339, 'naval': 25491, 'armada': 1885, 'battleship': 3431, 'navalcombat': 25495, 'jdsmyoko': 20000, 'lostcommunication': 22025, 'taser': 37051, 'buoy': 5271, 'communicationsexpert': 7895, 'jointchiefsofstaff': 20201, 'crashlanding': 8668, 'jetfighterpilot': 20089, 'navylieutenant': 25512, 'permissiontomarry': 27610, 'ussjohnpauljones': 39743, 'basedonboardgame': 2936, 'mightymo': 23623, 'ussmissouri': 39745, 'thriller action': 37852, 'sciencefiction fight': 32496, 'fight navy': 14381, 'navy mindreading': 25508, 'mindreading hongkong': 23741, 'hongkong soccer': 18022, 'soccer scientist': 34645, 'scientist fictionalwar': 32623, 'fictionalwar naval': 14342, 'naval armada': 25492, 'armada battleship': 1886, 'battleship navalcombat': 3432, 'navalcombat jdsmyoko': 25496, 'jdsmyoko lostcommunication': 20001, 'lostcommunication taser': 22026, 'taser buoy': 37052, 'buoy communicationsexpert': 5272, 'communicationsexpert jointchiefsofstaff': 7896, 'jointchiefsofstaff crashlanding': 20202, 'crashlanding jetfighterpilot': 8670, 'jetfighterpilot navylieutenant': 20090, 'navylieutenant permissiontomarry': 25513, 'permissiontomarry ussjohnpauljones': 27611, 'ussjohnpauljones basedonboardgame': 39744, 'basedonboardgame aftercreditsstinger': 2937, 'aftercreditsstinger mightymo': 617, 'mightymo ussmissouri': 23624, 'dna': 10581, 'tyrannosaurusrex': 39275, 'velociraptor': 39901, 'island': 19772, 'suspense': 36666, 'amusementpark': 1333, 'animalattack': 1462, 'themepark': 37754, 'jurassicpark': 20365, 'animalhorror': 1476, 'sciencefiction thriller': 32591, 'thriller monster': 38096, 'monster dna': 24186, 'dna tyrannosaurusrex': 10588, 'tyrannosaurusrex velociraptor': 39279, 'velociraptor island': 39902, 'island sequel': 19799, 'sequel suspense': 33213, 'suspense disaster': 36682, 'disaster escape': 10394, 'escape dinosaur': 12555, 'dinosaur amusementpark': 10325, 'amusementpark animalattack': 1334, 'animalattack themepark': 1470, 'themepark jurassicpark': 37756, 'jurassicpark 3d': 20366, '3d animalhorror': 101, 'sociopath': 34710, 'killer': 20584, 'artgallery': 2016, 'istanbulturkey': 19838, 'uzi': 39757, 'boobytrap': 4544, 'impersonatingapoliceofficer': 18896, 'macao': 22317, 'adventure thriller': 511, 'thriller spy': 38204, 'spy secretagent': 35433, 'secretagent sociopath': 32874, 'sociopath killer': 34713, 'killer artgallery': 20586, 'artgallery britishsecretservice': 2018, 'britishsecretservice istanbulturkey': 4942, 'istanbulturkey imax': 19839, 'imax uzi': 18842, 'uzi boobytrap': 39758, 'boobytrap impersonatingapoliceofficer': 4548, 'impersonatingapoliceofficer macao': 18898, 'pizzaboy': 27995, 'doctor': 10596, 'tentacle': 37508, 'death': 9666, 'supervillain': 36486, 'fantasy dualidentity': 13687, 'dualidentity loveofone': 11662, 'slife pizzaboy': 34397, 'pizzaboy marvelcomic': 27996, 'superhero doctor': 36339, 'doctor scientist': 10618, 'scientist tentacle': 32641, 'tentacle death': 37509, 'death supervillain': 9695, 'waronterror': 40712, 'tennessee': 37486, 'malibu': 22603, 'tonystark': 38452, 'ironman': 19756, 'mandarin': 22648, 'warmachine': 40690, 'ironpatriot': 19758, 'extremis': 13096, 'sciencefiction terrorist': 32590, 'terrorist waronterror': 37601, 'waronterror tennessee': 40717, 'tennessee malibu': 37488, 'malibu marvelcomic': 22605, 'basedoncomicbook tonystark': 2983, 'tonystark ironman': 38453, 'ironman aftercreditsstinger': 19757, 'aftercreditsstinger marvelcinematicuniverse': 615, 'marvelcinematicuniverse mandarin': 22988, 'mandarin 3d': 22649, '3d warmachine': 121, 'warmachine ironpatriot': 40691, 'ironpatriot extremis': 19759, 'queen': 29700, 'aliceinwonderland': 938, 'fantasy adventure': 13656, 'adventure basedonnovel': 412, 'fictionalplace queen': 14335, 'queen fantasy': 29705, 'fantasy aliceinwonderland': 13657, 'aliceinwonderland fantasyworld': 940, 'fantasyworld 3d': 13787, 'mutant': 25115, 'beast': 3504, 'cyclops': 9285, 'thriller mutant': 38102, 'mutant marvelcomic': 25123, 'marvelcomic basedoncomicbook': 22990, 'superhuman beast': 36377, 'beast cyclops': 3506, 'cyclops aftercreditsstinger': 9286, 'dormitory': 10841, 'games': 15615, 'bestfriend': 3697, 'university': 39529, 'scary': 32296, 'family monster': 13448, 'monster dormitory': 24187, 'dormitory games': 10844, 'games animation': 15616, 'animation bestfriend': 1521, 'bestfriend university': 3729, 'university scary': 39536, 'scary aftercreditsstinger': 32297, 'egypt': 12144, 'sun': 36284, 'chaos': 6313, 'symbol': 36894, 'artifact': 2031, 'transformers': 38783, 'tank': 37015, 'robot': 31113, 'adventure egypt': 437, 'egypt sun': 12154, 'sun chaos': 36285, 'chaos symbol': 6326, 'symbol artifact': 36895, 'artifact transformers': 2034, 'transformers tank': 38786, 'tank robot': 37019, 'robot imax': 31127, 'imax duringcreditsstinger': 18830, 'giantrobot': 16067, 'transformingrobot': 38787, 'adventure sequel': 498, 'sequel alien': 33159, 'alien transformers': 995, 'transformers giantrobot': 38784, 'giantrobot robot': 16071, 'imax transformingrobot': 18840, 'circus': 6971, 'hope': 18067, 'illusion': 18794, 'lost': 22010, 'magictrick': 22478, 'family circus': 13361, 'circus witch': 6978, 'magic hope': 22437, 'hope illusion': 18072, 'illusion lost': 18796, 'lost magictrick': 22014, 'magictrick wizard': 22479, 'wizard 3d': 41445, '

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [59]:
# 영화간 장르 유사도 비교
gen_key_sim = cosine_similarity(movie_gen_key, movie_gen_key)
print(gen_key_sim.shape)
gen_key_sim[:10, :10]

(4803, 4803)

array([[1.        , 0.0915018 , 0.09832103, 0.020004  , 0.16439899,
        0.0915018 , 0.        , 0.14893887, 0.09352195, 0.14893887],
       [0.0915018 , 1.        , 0.07347184, 0.02242243, 0.05264981,
        0.17948718, 0.        , 0.06677806, 0.10482848, 0.13355611],
       [0.09832103, 0.07347184, 1.        , 0.06424926, 0.15086286,
        0.14694367, 0.        , 0.19134595, 0.05006262, 0.14350946],
       [0.020004  , 0.02242243, 0.06424926, 1.        , 0.02302046,
        0.04484485, 0.        , 0.05839572, 0.        , 0.11679143],
       [0.16439899, 0.05264981, 0.15086286, 0.02302046, 1.        ,
        0.07897472, 0.0277885 , 0.20567735, 0.0358748 , 0.10283868],
       [0.0915018 , 0.17948718, 0.14694367, 0.04484485, 0.07897472,
        1.        , 0.        , 0.26711223, 0.06988566, 0.20033417],
       [0.        , 0.        , 0.        , 0.        , 0.0277885 ,
        0.        , 1.        , 0.03524537, 0.07377111, 0.        ],
       [0.14893887, 0.06677806, 0.19134595, 0.05839572, 0.20567735,
        0.26711223, 0.03524537, 1.        , 0.04550158, 0.26086957],
       [0.09352195, 0.10482848, 0.05006262, 0.        , 0.0358748 ,
        0.06988566, 0.07377111, 0.04550158, 1.        , 0.13650473],
       [0.14893887, 0.13355611, 0.14350946, 0.11679143, 0.10283868,
        0.20033417, 0.        , 0.26086957, 0.13650473, 1.        ]])

In [60]:
# 각 영화별 다른 영화들과의 유사도를 오름차순으로 정렬한 뒤, 열 순서를 뒤집어 내림차순(유사도 높은 순) 인덱스를 만든다.
movie_idx_by_gen_key_sim_desc = gen_key_sim.argsort(axis=-1)[:, ::-1]
print(movie_idx_by_gen_key_sim_desc.shape)

# 0번 영화와 유사도가 가장 높은 10개의 영화 인덱스
print(movie_idx_by_gen_key_sim_desc[0, :10])

(4803, 4803)
[   0  786   83   47   61 1652 3208 1932  193 4117]

In [61]:
# 0번 영화와 유사도가 가장 높은 10개의 영화
movie_df.iloc[movie_idx_by_gen_key_sim_desc[0, :10]]

,id,title,genres,vote_average,vote_count,popularity,keywords,overview,weighted_vote_average,gen_key
0,19995,Avatar,Action Adventure Fantasy ScienceFiction,7.2,11800,150.437577,cultureclash future spacewar spacecolony socie...,"In the 22nd century, a paraplegic Marine is di...",7.166301,Action Adventure Fantasy ScienceFiction cultur...
786,381902,The Monkey King 2,Action Adventure Fantasy,6.0,24,4.726290,monkeyking,Taking place 500 years after the Havoc in Heav...,6.086560,Action Adventure Fantasy monkeyking
83,79698,The Lovers,Action Adventure ScienceFiction Romance,4.8,34,2.418535,,The Lovers is an epic romance time travel adve...,5.983478,Action Adventure ScienceFiction Romance
47,54138,Star Trek Into Darkness,Action Adventure ScienceFiction,7.4,4418,78.291018,spacecraft friendship sequel futuristic space ...,When the crew of the Enterprise is called back...,7.298885,Action Adventure ScienceFiction spacecraft fri...
61,76757,Jupiter Ascending,ScienceFiction Fantasy Action Adventure,5.2,2768,85.369080,jupiter space womandirector 3d interspeciesrom...,In a universe where human genetic material is ...,5.305246,ScienceFiction Fantasy Action Adventure jupite...
1652,14164,Dragonball Evolution,Action Adventure Fantasy ScienceFiction Thriller,2.9,462,21.677732,karate superhero revenge dragon duringcreditss...,The young warrior Son Goku sets out on a quest...,4.320022,Action Adventure Fantasy ScienceFiction Thrill...
3208,333355,Star Wars: Clone Wars: Volume 1,Action Adventure Animation Fantasy ScienceFiction,8.0,27,1.881466,war spaceopera clonetroopers,"The Saga continues with the Emmy-winning ""Star...",6.221858,Action Adventure Animation Fantasy ScienceFict...
1932,24264,Sheena,Action Adventure Comedy Fantasy ScienceFiction,5.0,22,4.020194,africa mercenary adventure femalehero junglegirl,Sheena's white parents are killed while on Saf...,6.030907,Action Adventure Comedy Fantasy ScienceFiction...
193,82700,After Earth,ScienceFiction Action Adventure,5.0,2532,42.840582,dystopia,One thousand years after cataclysmic events fo...,5.139316,ScienceFiction Action Adventure dystopia
4117,24746,Six-String Samurai,Action Adventure ScienceFiction,5.8,36,1.892183,independentfilm,In a post-apocalyptic world where the Russians...,6.066277,Action Adventure ScienceFiction independentfilm

In [62]:
# 영화명을 전달하면 장르 유사도가 높은 영화 중 "가중평점"이 상위인 영화 10건을 추천하는 함수
def recommand_genre_similar_movies(title, top_n=10):
    # 제목으로 영화 인덱스 조회
    try:
        index = movie_df[movie_df['title'] == title].index.values[0]
    except:
        raise ValueError(f"해당 영화는 존재하지 않습니다. : {title}")

    # 장르 유사도 상위 top_n * 2 조회
    rcmd_movie_df = movie_df.iloc[movie_idx_by_gen_key_sim_desc[index, :top_n*2]]
    
    # 조회한 영화는 제외
    rcmd_movie_df = rcmd_movie_df[rcmd_movie_df.index != index]
    # 평점 상위 top_n건 추천
    return rcmd_movie_df.sort_values('weighted_vote_average', ascending=False)[:top_n]

recommand_genre_similar_movies('Avatar', 10)

,id,title,genres,vote_average,vote_count,popularity,keywords,overview,weighted_vote_average,gen_key
46,127585,X-Men: Days of Future Past,Action Adventure Fantasy ScienceFiction,7.5,6032,118.078691,1970s mutant timetravel marvelcomic basedoncom...,The ultimate X-Men ensemble fights a war for t...,7.418594,Action Adventure Fantasy ScienceFiction 1970s ...
47,54138,Star Trek Into Darkness,Action Adventure ScienceFiction,7.4,4418,78.291018,spacecraft friendship sequel futuristic space ...,When the crew of the Enterprise is called back...,7.298885,Action Adventure ScienceFiction spacecraft fri...
14,49521,Man of Steel,Action Adventure Fantasy ScienceFiction,6.5,6359,99.398009,savingtheworld dccomics superhero basedoncomic...,A young boy learns that he has extraordinary p...,6.477564,Action Adventure Fantasy ScienceFiction saving...
2317,157,Star Trek III: The Search for Spock,ScienceFiction Action Adventure Thriller,6.4,434,15.314027,,Admiral Kirk and his bridge crew risk their ca...,6.258296,ScienceFiction Action Adventure Thriller
3208,333355,Star Wars: Clone Wars: Volume 1,Action Adventure Animation Fantasy ScienceFiction,8.0,27,1.881466,war spaceopera clonetroopers,"The Saga continues with the Emmy-winning ""Star...",6.221858,Action Adventure Animation Fantasy ScienceFict...
1191,11551,Small Soldiers,Comedy Adventure Fantasy ScienceFiction Action,6.2,511,23.088571,defenseindustry toyshop technicaltoy soldier p...,When missile technology is used to enhance toy...,6.154700,Comedy Adventure Fantasy ScienceFiction Action...
2681,15173,Jonah: A VeggieTales Movie,Action Adventure Animation Comedy Family Fanta...,6.4,22,1.446172,,"Get ready as Bob the Tomato, Larry the Cucumbe...",6.109439,Action Adventure Animation Comedy Family Fanta...
2708,41317,Caravans,Action Adventure Drama Romance,5.8,1,0.633004,,This epic adventure-drama based on James Miche...,6.091384,Action Adventure Drama Romance
786,381902,The Monkey King 2,Action Adventure Fantasy,6.0,24,4.726290,monkeyking,Taking place 500 years after the Havoc in Heav...,6.086560,Action Adventure Fantasy monkeyking
4117,24746,Six-String Samurai,Action Adventure ScienceFiction,5.8,36,1.892183,independentfilm,In a post-apocalyptic world where the Russians...,6.066277,Action Adventure ScienceFiction independentfilm