## Pandas 인덱싱과 수정
 - 간단한 선택, 필터링, 추가/삭제, 수정 등을 익혀본다.

## 열 선택
열 하나를 선택하면 Series, 여러 열을 선택하면 DataFrame이다.

In [31]:
import pandas as pd
     

df = pd.DataFrame({
    '이름': ['김민수', '이영희', '박철수', '최지영'],
    '부서': ['영업', '개발', '인사', '마케팅'],
    '급여': [4500, 5200, 3800, 4800],
    '입사년도': [2019, 2018, 2021, 2020]
})

print(df['이름']) # Series
print()
print(df[['이름', '급여']]) # DataFrame

0    김민수
1    이영희
2    박철수
3    최지영
Name: 이름, dtype: str

    이름    급여
0  김민수  4500
1  이영희  5200
2  박철수  3800
3  최지영  4800

## 행 선택 : loc, iloc, at, iat
 - loc : 라벨 기준
 - iloc : 위치 기준
 - at, iat : 단일 셀 값만 빠르게 접근 (슬라이싱/복수선택 불가)

In [32]:
products = pd.DataFrame({
    '상품': ['노트북', '마우스', '키보드', '모니터'],
    '가격': [1200000, 25000, 45000, 350000],
    '재고': [10, 50, 30, 15]
}, index=['P001', 'P002', 'P003', 'P004'])

print(products.loc['P002']) # 라벨 기반 행 선택
print()
print(products.iloc[0])     # 위치 기반 행 선택
print()
print(products.loc['P001':'P003'])  # 라벨 기반 슬라이싱은 끝을 포함
print()
print(products.iloc[0:2])           # 위치 기반 슬라이싱은 끝을 미포함

상품      마우스
가격    25000
재고       50
Name: P002, dtype: object

상품        노트북
가격    1200000
재고         10
Name: P001, dtype: object

       상품       가격  재고
P001  노트북  1200000  10
P002  마우스    25000  50
P003  키보드    45000  30

       상품       가격  재고
P001  노트북  1200000  10
P002  마우스    25000  50

In [33]:
# 특정 셀 접근
print(products.loc['P002','가격'])
print(products.iloc[1,1])
# 간결한 접근
print(products.at['P002','가격'])
print(products.iat[1,1])

25000
25000
25000
25000

## 조건 필터링
조건식의 결과(True/False)로 원하는 행만 고른다.

In [34]:
employees = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최지영', '정다은'],
    '나이': [28, 35, 42, 31, 26],
    '부서': ['개발', '영업', '개발', '인사', '영업'],
    '급여': [4200, 5100, 6500, 4800, 3900]
})

print(employees['나이'] >= 30)  # 조건식의 결과 Boolean Series 반환
print()
print(employees[employees['나이'] >= 30])
print()
print(employees[employees['부서']=='개발'])

0    False
1     True
2     True
3     True
4    False
Name: 나이, dtype: bool

    이름  나이  부서    급여
1  이영희  35  영업  5100
2  박민수  42  개발  6500
3  최지영  31  인사  4800

    이름  나이  부서    급여
0  김철수  28  개발  4200
2  박민수  42  개발  6500

## 복합 조건과 isin, query
여러 조건을 동시에 적용할 때 논리 연산자를 사용한다.
 - & : AND
 - | : OR
 - ~ : NOT
주의
 - 각 조건은 반드시 괄호로 묶어야 한다.
  
isin() : 특정 값 집합에 포함되는지 확인
query() : 문자열 기반으로 조건을 작성하는 방법으로 SQL의 WHERE처럼 읽기 쉬운 표현이 가능

In [35]:
# 나이가 30세 이상이고, 급여가 5000만원 이상인 직원 필터링
print(employees[(employees['나이'] >= 30)&(employees['급여'] >= 5000)]) # 반드시 기호 사용
# 개발 또는 영업 부서인 직원 필터링
print(employees[employees['부서'].isin(['개발','영업'])])
# and, or -> 파이썬 문법으로 query에서민 사용
employees.query('나이 >= 30 and 급여 >= 5000')

    이름  나이  부서    급여
1  이영희  35  영업  5100
2  박민수  42  개발  6500
    이름  나이  부서    급여
0  김철수  28  개발  4200
1  이영희  35  영업  5100
2  박민수  42  개발  6500
4  정다은  26  영업  3900

    이름  나이  부서    급여
1  이영희  35  영업  5100
2  박민수  42  개발  6500

## 열 추가와 행 추가
계산 결과로 새 열을 만들거나, 새 행을 붙일 수 있다.

In [36]:
sales = pd.DataFrame({
    '상품': ['A', 'B', 'C'],
    '수량': [10, 20, 15],
    '단가': [1000, 2000, 1500]
})

sales['총액'] = sales['수량']*sales['단가'] # 계산 결과로 새 열 추가
sales['국가'] = '대한민국'                  # 고정값 새 열 추가
sales

  상품  수량    단가     총액    국가
0  A  10  1000  10000  대한민국
1  B  20  2000  40000  대한민국
2  C  15  1500  22500  대한민국

In [37]:
# 새로운 행을 DataFrame 형태로 생성
new_row = pd.DataFrame({
    '상품' : ['D'],
    '수량' : [25],
    '단가' : [1800],
    '총액' : [25*18000],
    '국가' : ['대한민국']
    })

# Pandas는 index 중복을 허용하지만, 중복 되지 않게 관리하는 것이 좋다.
# ignore_index=True -> 기존 인덱스를 유지하지 않고 새롭게 0부터 다시 번호 부여
sales = pd.concat([sales, new_row], ignore_index=True)
sales

  상품  수량    단가      총액    국가
0  A  10  1000   10000  대한민국
1  B  20  2000   40000  대한민국
2  C  15  1500   22500  대한민국
3  D  25  1800  450000  대한민국

## 열 삭제와 행 삭제
drop은 원본을 수정하지 않고 새로운 DataFrame을 반환한다.

In [38]:
# axis=1 열 삭제
print(sales.drop('국가', axis = 1))
print()

# axis=0 행 삭제 default
print(sales.drop(0))
print()

print(sales)    # 원본이 보존 되고 있음
print()

# 원본을 직접 수정하려면 inplace=True 사용
sales.drop('국가', axis=1, inplace=True)
print()

print(sales)
print()

# 여러 개 삭제도 가능
print(sales.drop(['수량','단가'],axis=1))

print(sales)
print()

  상품  수량    단가      총액
0  A  10  1000   10000
1  B  20  2000   40000
2  C  15  1500   22500
3  D  25  1800  450000

  상품  수량    단가      총액    국가
1  B  20  2000   40000  대한민국
2  C  15  1500   22500  대한민국
3  D  25  1800  450000  대한민국

  상품  수량    단가      총액    국가
0  A  10  1000   10000  대한민국
1  B  20  2000   40000  대한민국
2  C  15  1500   22500  대한민국
3  D  25  1800  450000  대한민국


  상품  수량    단가      총액
0  A  10  1000   10000
1  B  20  2000   40000
2  C  15  1500   22500
3  D  25  1800  450000

  상품      총액
0  A   10000
1  B   40000
2  C   22500
3  D  450000
  상품  수량    단가      총액
0  A  10  1000   10000
1  B  20  2000   40000
2  C  15  1500   22500
3  D  25  1800  450000

## 값 수정과 열 이름 변경
 - loc을 사용하면 특정 위치 또는 조건에 맞는 값을 쉽게 수정할 수 있다.
 - 조건식을 활용하면 여러 행을 한 번에 수정할 수 있다.

In [43]:
items = pd.DataFrame({
    '상품명': ['노트북', '마우스', '키보드'],
    '가격': [1500000, 30000, 50000],
    '카테고리': ['전자기기', '전자기기', '전자기기']
})

# 특정 셀 값 수정 (행 + 열 지정)
items.loc[0, '가격'] = 1400000

# 조건 기반으로 값 수정
# 가격이 100만원 미만인 상품은 소형기기로 카테고리 변경하기
items.loc[items['가격'] < 1000000 , '카테고리'] = '소형기기'

# 열 이름 변경
items = items.rename(columns={'상품명': 'Product', '가격': 'Price'})

items

  Product    Price  카테고리
0     노트북  1400000  전자기기
1     마우스    30000  소형기기
2     키보드    50000  소형기기

## 데이터 타입 변경
astype()으로 열의 타입을 변경한다.

In [47]:
df_type = pd.DataFrame({
    'A': ['1', '2', '3'],
    'B': [1.5, 2.5, 3.5]
})

print(df_type.dtypes)
print()

df_type['A'] = df_type['A'].astype(int)
print(df_type)
print(df_type.dtypes)

df_type = df_type.astype({'A': float, 'B': int})
print(df_type)
print(df_type.dtypes)

A        str
B    float64
dtype: object

   A    B
0  1  1.5
1  2  2.5
2  3  3.5
A      int64
B    float64
dtype: object
     A  B
0  1.0  1
1  2.0  2
2  3.0  3
A    float64
B      int64
dtype: object